//Authentication
export const GET_USER = 'GET_USER';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const LOG_OUT = 'LOG_OFF';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const IS_LOADING = 'IS_LOADING';
export const CLEAR_MSG = 'CLEAR_MSG';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const ERROR_CHANGE_PASSWORD = 'ERROR_CHANGE_PASSWORD'
//Note types
export const GET_NOTES = 'GET_NOTES';
export const ADD_NOTE = 'ADD_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const CLEAN_NOTES = 'CLEAN_NOTES';
export const UPDATE_COORDINATE = 'UPDATE_COORDINATE';
export const SHOW_IMAGE_OVERLAY = 'SHOW_IMAGE_OVERLAY';
export const HIDE_IMAGE_OVERLAY = 'HIDE_IMAGE_OVERLAY';
export const SHOW_ERROR_NOTE = 'SHOW_ERROR_NOTE';
export const HIDE_ERROR_NOTE = 'HIDE_ERROR_NOTE';
//Notes Company Types
export const GET_NOTES_COMPANY = 'GET_NOTES_COMPANY';
export const ADD_NOTE_COMPANY = 'ADD_NOTE_COMPANY';
export const DELETE_NOTE_COMPANY = 'DELETE_NOTE_COMPANY';
export const UPDATE_NOTE_COMPANY = 'UPDATE_NOTE_COMPANY';
export const CLEAN_NOTES_COMPANY = 'CLEAN_NOTES_COMPANY';
export const UPDATE_COORDINATE_NOTES_COMPANY = 'UPDATE_COORDINATE_NOTES_COMPANY';
export const SHOW_IMAGE_COMPANY_OVERLAY = 'SHOW_IMAGE_COMPANY_OVERLAY';
export const HIDE_IMAGE_COMPANY_OVERLAY = 'HIDE_IMAGE_COMPANY_OVERLAY';
export const SHOW_ERROR_COMPANY_NOTES = 'SHOW_ERROR_COMPANY_NOTES';
export const HIDE_ERROR_COMPANY_NOTES = 'HIDE_ERROR_COMPANY_NOTES';
//Projects
export const GET_PROJECT_LIST = 'GET_PROJECT_LIST';
export const GET_PROJECT_BY_ID = 'GET_PROJECT_BY_ID';
export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const LEAVE_PROJECT = "LEAVE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const CLEAR_PROJECT_MSG = "CLEAR_PROJECT_MSG";
//Meetings
export const CREATE_MEETING = "CREATE_MEETING";
export const GET_ROOMS_LIST = 'GET_ROOMS_LIST';
export const GET_ROOM = 'GET_ROOM';
export const GET_MEETINGS_REMINDER = 'GET_MEETINGS_REMINDER';
export const CLEAN_ROOM = 'CLEAN_ROOM';
export const ROOM_DENIED = 'ROOM_DENIED';
export const SAVE_MEETING = 'SAVE_MEETING';
export const DELETE_MEETING = 'DELETE_MEETING';
//Notifications
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const SHOW_NEXT_MEETING = 'SHOW_NEXT_MEETING'
export const UPDATE_REMINDERS = 'UPDATE_REMINDERS';
export const UPDATE_NEXT_MEETING = 'UPDATE_NEXT_MEETING';
export const POSPONE_MEETING = 'POSPONE_MEETING';
export const CLEAR_POSPONE = 'CLEAR_POSPONE';
export const DISCARD_MEETING = 'DISCARD_MEETING';
export const CHECK_TIME = 'CHECK_TIME';
//Files
export const UPLOADING_IMAGE = 'UPLOADING_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR';
export const SHOW_ERROR_IMAGE = 'SHOW_ERROR_IMAGE';
export const HIDE_ERROR_IMAGE = 'HIDE_ERROR_IMAGE'
//Organizations
export const GET_ORGANIZATIONS = 'GET_ORGANIZATIONS';
export const CREATE_ORGANIZATION = 'CREATE_ORGANIZATION';
export const GET_ACTUAL_ORGANIZATION = 'GET_ACTUAL_ORGANIZATION';
export const CLEAN_ACTUAL_ORGANIZATION = 'CLEAN_ACTUAL_ORGANIZATION';
export const CLEAN_ORGANIZATION_MESSAGE = 'CLEAN_ORGANIZATION_MESSAGE'